[package]
name = "vcf2parquet"
version = "0.1.1"
edition = "2024"

[dependencies]
arrow = "55.1.0"
clap = { version = "4.5.39", features = ["derive"] }
flate2 = "1.1.2"
parquet = { version = "55.1.0", features = ["arrow"] }
