[project]
name = "vcf2parquet"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastparquet>=2024.11.0",
    "typer>=0.16.0",
]

[project.scripts]
vcf2parquet = "vcf2parquet:main"
